[package]
name = "view-fractals"
version = "0.1.0"
authors = ["Thomas Lienbacher <lienbacher.tom@gmail.com>"]
edition = "2018"

[dependencies]
num = "0.2"
minifb = "0.16"
rand = "0.7"
interpolation = "0.2"
palette = "0.5"
rayon = "1.3"
